name: Bug Report
description: Bugs in the software itself
labels: [bug]
body:
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
        required: true
      - label: My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the next checkbox. I will try the last two checkboxes in the checklist.
      - label: I have checked that this issue isn't addressed in any other issue or pull request.
        required: true
      - label: I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
      - label: I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
      - label: https://github.com/SaschaWillems/VulkanCapsViewer reports Vulkan capabilities.
- type: textarea
  attributes: 
    label: Describe the Bug
    description: 💥 What's the bug?
  validations:
    required: true
    
- type: textarea
  attributes: 
    label: To Reproduce 
    description: 🧙 How can we emulate the bug on our own machine? (Please write in steps)
  validations:
    required: true

- type: input
  attributes:
    label: Version (or commit hash)
    description: ✍️ What version of Upscayl did you use? If you used Mac App Store version, please mention it!
  validations:
    required: true

- type: dropdown
  attributes:
    label: Platform
    description: 🧑‍💻 What operating system or distribution platform do you use? Select the last one that applies.
    options:
      - Linux
      - macOS .dmg / Homebrew
      - Mac App Store
      - Flatpak
      - Windows
  validations:
    required: true

- type: input
  attributes:
    label: OS Version
    description: "✍️ What's the version of your operating system? (Example: Ubuntu 22.04, MacOS Monterey or Windows 10)"
  validations:
    required: true

- type: input
  attributes:
    label: GPU Name
    description: 📝 What GPU do you have? If you do not know, please just write your device name if it's a laptop. If the name is something like "Intel Graphics" or "AMD Vega" and you can't Upscayl images, STOP and read the third bullet point of the FAQ. 
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Expected Behavior
    description: 🤓 What should've happened?
  validations:
    required: false
    
- type: textarea
  attributes:
    label: Screenshots
    description: 🤳 Got screenshots?

- type: textarea
  attributes: 
    label: Paste the logs
    description: 💥 Paste the logs below. ([Here's a Guide if you don't know how to do that](https://github.com/upscayl/upscayl/wiki/Guide#logs))
    render: sh
  validations:
    required: true
